FROM oven/bun:1.1.12-alpine

RUN apk update && apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
ENV CHROME_BIN=/usr/bin/chromium-browser \
    CHROME_PATH=/usr/lib/chromium/

WORKDIR /app

COPY package.json bun.lockb ./

ENV NODE_ENV=production

RUN bun install --frozen-lockfile --production

COPY . .

USER bun

EXPOSE 4000/tcp

ENTRYPOINT ["bun", "run", "start"]